-- Remover primeiro as tabelas dependentes evita violações de chave estrangeira.
DROP TABLE IF EXISTS playlist_musicas;
DROP TABLE IF EXISTS reproducoes;
DROP TABLE IF EXISTS playlists;
DROP TABLE IF EXISTS musicas;

CREATE TABLE musicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    artista VARCHAR(150) NOT NULL,
    album VARCHAR(150),
    duracao INTEGER NOT NULL CHECK (duracao > 0),
    genero VARCHAR(50)
);

CREATE TABLE playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255)
);

CREATE TABLE playlist_musicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlistid BIGINT NOT NULL,
    musicaid BIGINT NOT NULL,
    CONSTRAINT fk_vinculo_playlist FOREIGN KEY (playlistid) REFERENCES playlists(id),
    CONSTRAINT fk_vinculo_musica FOREIGN KEY (musicaid) REFERENCES musicas(id),
    CONSTRAINT uk_playlist_musica UNIQUE (playlistid, musicaid)
);

CREATE TABLE reproducoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlistid BIGINT NOT NULL,
    datahora TIMESTAMP NOT NULL,
    CONSTRAINT fk_reproducao_playlist FOREIGN KEY (playlistid) REFERENCES playlists(id)
);

CREATE INDEX idx_vinculo_musica ON playlist_musicas(musicaid);
CREATE INDEX idx_reproducao_playlist ON reproducoes(playlistid);
